server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/laptopShop"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: laptopshop
    server: http://localhost:${server.port}
    title: Laptop Shop API
    version: 1.0.0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: uploads

app:
  image-api-base-url: "http://localhost:8080/images/"


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"